name: Deploy to EB

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      MONGO_LIVE: ${{ secrets.MONGO_LIVE }}
      MONGO_TEST: ${{ secrets.MONGO_TEST }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*' 'node_modules/*'

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        version_label: v1.3.6
        application_name: motivateme
        environment_name: ${{ github.ref_name == 'main' && 'Motivateme-env' || 'Motivateme-env-1' }}
        region: ap-south-1
        deployment_package: deploy.zip

    - name: Notify of deployment
      run: echo "Deployed ${{ github.ref_name }} to Elastic Beanstalk"
